### PR TITLE
Add Swift Package Manager Support

### PR DESCRIPTION
**Pull request by alephao**
Hey guys, to solve the MaterialMotion library [issue #74](https://github.com/material-motion/material-motion-swift/issues/74), it's necessary to implement the Swift Package Manager Support here first, because this is a dependency 

Rename “tests/unit” to “tests/IndefiniteObservableTests” because “unit” is not a valid name for Swift Package Manager. The folder name needs to match the library name, and it needs to have a “Tests” suffix

Add some instructions on README.md for Swift PM

### CODE REVIEW

**Comment by randcode-generator** [comment]
It is suppose to be equivalent to ```pod install```. I don't see xcworkspace when I run ```swift build```

**Comment by jverkoey** [comment]
Is it possible to rename the "tests" folder rather than the "unit" folder?

**Comment by alephao** [comment]
@randcode-generator From what I know, SPM does not have support for iOS yet. Devs who want to use SPM have to do some manual work or [use some kind of automated script](https://www.cocoawithlove.com/blog/package-manager-fetch.html#some-kind-of-automated-script). 

Can you show me where you saw this thing about .xcworkspace? I would be happy to implement it.

@jverkoey I tried, but I don't think it's possible due to [SE-0129](https://github.com/apple/swift-package-manager/blob/43cc5da9ef3e65d9b6bff555b4d18866abd5b0a0/CHANGELOG.md)

**Comment by randcode-generator** [comment]
```
swift package generate-xcodeproj
```

**Comment by alephao** [comment]
This command is working well, but I don't think it is supposed to be used for your iOS project

**Review by jverkoey — DISMISSED** [review]
This looks good as a first pass. It's interesting that our `src` directory is being picked up when the Swift convention appears to be `Sources`.

**Comment by jverkoey** [comment]
A couple quick follow-up requests:

- [ ] Add `IndefiniteObservable.xcodeproj` to the .gitignore.
- [ ] Fix the spacing on `name: "YourProject",` in the README.

**Comment by alephao** [comment]
They describe what folder names are accepted by SPM here [PackageDescriptionV4](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#target-format-reference) :)

> the Package Manager will look for a directory matching the name of the target in these places:
> 
> Regular targets: package root, Sources, Source, src, srcs.
> Regular targets: Tests, package root, Sources, Source, src, srcs.

**Review by jverkoey — APPROVED** [review]

**Comment by jverkoey** [comment]
Thank you kindly!

**Pull request merged**
